const types = {
  // user
  SUCCESS_JOIN: 'SUCCESS_JOIN',
  SUCCESS_LOGIN: 'SUCCESS_LOGIN',

  // area
  LOADING_GET_AREA: 'LOADING_GET_AREA',
  SUCCESS_GET_AREA: 'SUCCESS_GET_AREA',
  FAIL_GET_AREA: 'FAIL_GET_AREA',

  SELECT_AREA: 'SELECT_AREA',

  // travle
  SAVE_TRAVLE_OPTION: 'SAVE_TRAVLE_OPTION',
  SELECT_LOCATION: 'SELECT_LOCATION',
  SUCCESS_POST_LOCATION: 'SUCCESS_POST_LOCATION',
  CLEAR_LOCATION: 'CLEAR_LOCATION',
};

export default types;
